.husky/pre-commit, package-lock.json, package.json, start-containers.sh
Added husky check that will prevent direct commits on the main branch
=> chore: 🤖 Prevented direct commit on main branch

.husky/pre-push
=> chore: 🤖 allowed pushing of tags in main branch

docker-compose.yml
added phpmyadmin to docker composer
✅ Closes: 7
=> chore: 🤖 Added phpmyadmin

custom-plugins/fictive_studios/admin/migrations/create-tables.php, custom-plugins/fictive_studios/admin/migrations/print-types.php, custom-plugins/fictive_studios/admin/print-types/listing/partials/print-types-header.php, custom-plugins/fictive_studios/admin/print-types/listing/print-types-listing-helper.php, custom-plugins/fictive_studios/admin/print-types/listing/print-types-listing.php, custom-plugins/fictive_studios/builder.php, custom-plugins/fictive_studios/includes/class-builder.php
added print type pages
✅ Closes: #14
=> feat: 🎸 Print Type Page

custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing-helper.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/partials/fashion-designs-header.php, custom-plugins/fictive_studios/admin/migrations/create-tables.php, custom-plugins/fictive_studios/admin/migrations/fashion-designs.php, custom-plugins/fictive_studios/builder.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 fashion designs list

docker-compose.yml, express/index.js, express/node.dockerfile, nginx/default.conf, package-lock.json, package.json, start-containers.sh
=> added fictive codes and woocommerce

custom-plugins/fictive_studios/admin/migrations/create-tables.php, custom-plugins/fictive_studios/admin/migrations/models.php, custom-plugins/fictive_studios/admin/models/listing/models-listing-helper.php, custom-plugins/fictive_studios/admin/models/listing/models-listing.php, custom-plugins/fictive_studios/admin/models/listing/partials/models-listing.php, custom-plugins/fictive_studios/builder.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 models list page

custom-plugins/fictive_studios/admin/printing-area/api/print-area-api.js, custom-plugins/fictive_studios/admin/printing-area/api/print-area-api.php, custom-plugins/fictive_studios/admin/printing-area/listing/printing-area-listing.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 get all print areas api

custom-plugins/fictive_studios/admin/printing-area/api/print-area-api.php, custom-plugins/fictive_studios/admin/printing-area/create/print-area-create-view.php, custom-plugins/fictive_studios/admin/printing-area/create/print-area-create.php, custom-plugins/fictive_studios/admin/printing-area/listing/partials/printing-area-header.php, custom-plugins/fictive_studios/admin/printing-area/listing/printing-area-listing-helper.php, custom-plugins/fictive_studios/admin/printing-area/listing/printing-area-listing.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 Added print area edit

custom-plugins/fictive_studios/admin/models/api/models-api.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 added models get api

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/admin/fashion-designs/create/fashion-design-create-view.php, custom-plugins/fictive_studios/admin/fashion-designs/create/fashion-design-create.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing-helper.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/partials/fashion-designs-header.php, custom-plugins/fictive_studios/admin/migrations/fashion-designs.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 added design upload

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/includes/class-builder.php
=> feat: 🎸 get api for fashion design

custom-plugins/fictive_studios/admin/migrations/create-tables.php, custom-plugins/fictive_studios/admin/migrations/sample-values/designs-sample.php, custom-plugins/fictive_studios/admin/migrations/sample-values/patterns-sample.php, custom-plugins/fictive_studios/admin/three-d-products/listing/3d-builder.js, express/src/templates/3d-builder/index.html, express/src/templates/3d-builder/my-designs.html, express/src/templates/3d-builder/patterns.html
=> feat: 🎸 added pattern and design to 3d editor

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/admin/fashion-designs/create/fashion-design-create-view.php
=> feat: 🎸 changed design layer to text

custom-plugins/fictive_studios/admin/woo-products-functionalities/woo-product-api.php, custom-plugins/fictive_studios/includes/class-admin-builder.php
=> feat: 🎸 woo product create

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/admin/fashion-designs/create/fashion-design-create.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing-helper.php, custom-plugins/fictive_studios/admin/migrations/fashion-designs.php, custom-plugins/fictive_studios/admin/migrations/models.php, custom-plugins/fictive_studios/admin/migrations/patterns.php, custom-plugins/fictive_studios/admin/migrations/print-area-model-coordinates.php, custom-plugins/fictive_studios/admin/migrations/print-types.php, custom-plugins/fictive_studios/admin/migrations/printing-areas.php, custom-plugins/fictive_studios/admin/migrations/sample-values/designs-sample.php, custom-plugins/fictive_studios/admin/migrations/sample-values/models-sample.php, custom-plugins/fictive_studios/admin/migrations/sample-values/patterns-sample.php, custom-plugins/fictive_studios/admin/migrations/sample-values/print-area-model-coordinates-sample.php, custom-plugins/fictive_studios/admin/migrations/sample-values/print-areas-sample.php, custom-plugins/fictive_studios/admin/migrations/templates.php, custom-plugins/fictive_studios/admin/model-print-areas/api/model-print-areas-api.php, custom-plugins/fictive_studios/admin/model-print-areas/create/model-print-areas-create.php, custom-plugins/fictive_studios/admin/model-print-areas/listing/model-print-areas-helper.php, custom-plugins/fictive_studios/admin/model-print-areas/listing/model-print-areas-listing.php, custom-plugins/fictive_studios/admin/models/api/models-api.php, custom-plugins/fictive_studios/admin/models/listing/models-listing-helper.php, custom-plugins/fictive_studios/admin/patterns/api/patterns-api.php, custom-plugins/fictive_studios/admin/patterns/listing/patterns-listing-helper.php, custom-plugins/fictive_studios/admin/print-types/listing/print-types-listing-helper.php, custom-plugins/fictive_studios/admin/printing-area/api/print-area-api.php, custom-plugins/fictive_studios/admin/printing-area/create/print-area-create.php, custom-plugins/fictive_studios/admin/printing-area/listing/printing-area-listing-helper.php, custom-plugins/fictive_studios/admin/templates/create/templates-create.php, custom-plugins/fictive_studios/admin/templates/listing/template-listing-helper.php, custom-plugins/fictive_studios/builder.php
=> fix: 🐛 changed data table prefix

custom-plugins/fictive_studios/admin/patterns/api/patterns-api.php, custom-plugins/fictive_studios/admin/patterns/create/patterns-create-view.php, custom-plugins/fictive_studios/admin/patterns/create/patterns-create.php, custom-plugins/fictive_studios/admin/patterns/listing/patterns-listing-helper.php, custom-plugins/fictive_studios/includes/class-admin-builder.php
added patterns edit
✅ Closes: #64
=> feat: 🎸 added patterns edit

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/admin/fashion-designs/create/fashion-design-create-view.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing-helper.php, custom-plugins/fictive_studios/admin/migrations/fashion-designs.php, custom-plugins/fictive_studios/admin/migrations/sample-values/designs-sample.php
=> feat: 🎸 added color and name to design layers

custom-plugins/fictive_studios/admin/print-types/api/print-types-api.php, custom-plugins/fictive_studios/admin/print-types/create/print-types-create-view.php, custom-plugins/fictive_studios/admin/print-types/create/print-types-create.php, custom-plugins/fictive_studios/admin/print-types/listing/partials/print-types-header.php, custom-plugins/fictive_studios/admin/print-types/listing/print-types-listing-helper.php, custom-plugins/fictive_studios/admin/print-types/listing/print-types-listing.php, custom-plugins/fictive_studios/includes/class-admin-builder.php
=> feat: 🎸 added print type crud

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/admin/fashion-designs/create/fashion-design-create-view.php, custom-plugins/fictive_studios/admin/fashion-designs/listing/fashion-designs-listing-helper.php, custom-plugins/fictive_studios/admin/layers/api/layers-api.php, custom-plugins/fictive_studios/admin/layers/create/layers-create-view.php, custom-plugins/fictive_studios/admin/layers/create/layers-create.php, custom-plugins/fictive_studios/admin/layers/listing/layers-listing-helper.php, custom-plugins/fictive_studios/admin/layers/listing/layers-listing.php, custom-plugins/fictive_studios/admin/layers/listing/partials/layers-header.php, custom-plugins/fictive_studios/admin/migrations/create-tables.php, custom-plugins/fictive_studios/admin/migrations/fashion-designs.php, custom-plugins/fictive_studios/admin/migrations/layers.php, custom-plugins/fictive_studios/builder.php, custom-plugins/fictive_studios/includes/class-admin-builder.php
restructured new design to have new layer table and added related crud
✅ Closes: #72
=> feat: 🎸 added new layers table

custom-plugins/fictive_studios/admin/fashion-designs/api/fashion-design-api.php, custom-plugins/fictive_studios/includes/class-admin-builder.php
=> feat: 🎸 api for design by model id

custom-plugins/fictive_studios/admin/user-designs/api/user-designs-api.php, custom-plugins/fictive_studios/builder.php, custom-plugins/fictive_studios/includes/class-admin-builder.php, custom-plugins/fictive_studios/includes/class-end-user-design-page.php, custom-plugins/fictive_studios/includes/private-products-handler.php, custom-plugins/fictive_studios/includes/woo-products-filter.php
=> feat: 🎸 added end user design save flow
